version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stratum_postgres
    restart: unless-stopped
    # network_mode: host
    environment:
      POSTGRES_USER: stratum
      POSTGRES_PASSWORD: stratum_pass
      POSTGRES_DB: stratum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stratum -d stratum"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: stratum_redis
    restart: unless-stopped
    # network_mode: host
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stratum_app
    restart: unless-stopped
    env_file:
      - .env    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # environment:
    #   DATABASE_URL: postgresql://stratum:stratum_pass@postgres:5432/stratum
    #   BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
    #   BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
    #   STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    #   STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    #   STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    #   NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    #   RESEND_API_KEY: ${RESEND_API_KEY}
    #   RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL:-orders@stratum.store}
    #   NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    #   ADMIN_EMAIL: ${ADMIN_EMAIL}
    #   MINIO_ENDPOINT: minio
    #   MINIO_PORT: 9000
    #   MINIO_USE_SSL: "false"
    #   MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-stratum}
    #   MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-stratum_minio_pass}
    #   MINIO_BUCKET: ${MINIO_BUCKET:-stratum-custom-orders}
    #   MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL:-http://localhost:9000}
    #   REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    #   NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/app/public/uploads


volumes:
  postgres_data:
  uploads_data:
  redis_data:
